#!/bin/bash

DIST_FOLDER=_dist
SLIM_FOLDER=_slim

echo "-- Building Site --"
hugo --destination ${DIST_FOLDER}

echo "-- Compressing Images --"
cp -r ${DIST_FOLDER} ${SLIM_FOLDER}
slimpack ${DIST_FOLDER}

echo "-- Deploying to Surge --"
surge ${SLIM_FOLDER}

echo "-- Removing Build Folder --"
rm -r ${DIST_FOLDER} ${SLIM_FOLDER}
